export type MemeDatabaseEntry = {
	title: string
	tags: string[]
}

export const MEMES_DATABASE: Record<string, MemeDatabaseEntry> = {
	"achha.webp": {
		title: "Achha Lode",
		tags: [
			"achha lode",
			"sarcastic doraemon",
			"sarcastic",
			"doraemon",
			"nobita",
			"indian",
			"hindi",
		],
	},
	"anya-forger.gif": {
		title: "Anya Forger Smug Smile",
		tags: [
			"anya forger",
			"spy x family",
			"smug grin",
			"heh",
			"scheming",
			"knowing look",
			"satisfied",
			"anime reaction",
		],
	},
	"baby-laugh-ai-baby.gif": {
		title: "Laughing Baby",
		tags: [
			"laughing baby",
			"giggling baby",
			"happy baby",
			"cute",
			"wholesome",
			"amused",
			"infant laugh",
		],
	},
	"bamboozled-astonished.gif": {
		title: "Staring Wide Eyed Man",
		tags: [
			"astonished",
			"wide eyes",
			"staring",
			"shock",
			"disbelief",
			"bamboozled",
			"wtf",
			"what",
		],
	},
	"betrayal-phone.gif": {
		title: "Shocked Blue Cat Phone",
		tags: [
			"blue cat",
			"phone",
			"checking phone",
			"bad news",
			"betrayal",
			"traumatized",
			"realization",
			"shocking news",
		],
	},
	"blinking-eyes-white-guy.gif": {
		title: "Blinking White Guy",
		tags: [
			"drew scanlon",
			"blinking guy",
			"blinking",
			"confused",
			"disbelief",
			"double take",
			"processing",
			"awkward",
		],
	},
	"blush.gif": {
		title: "Blushing While Reading Phone",
		tags: [
			"blushing",
			"texting",
			"in bed",
			"phone",
			"crush",
			"staring",
			"wholesome",
		],
	},
	"bobawooyo-dog-confused.gif": {
		title: "Surprised Dog Wait What",
		tags: [
			"dog",
			"wait what",
			"shocked",
			"surprised",
			"confused",
			"astonished",
			"bewildered",
		],
	},
	"bund-mraa.png": {
		title: "Bund Mraa",
		tags: [
			"punjabi",
			"pointing",
			"field",
			"insult",
			"aggressive",
			"go away",
			"sukhbir singh badal",
		],
	},
	"cast-net-fishing-fall.gif": {
		title: "Man Falls Throwing Net",
		tags: [
			"fishing",
			"fail",
			"boat",
			"falling",
			"water",
			"net",
			"accident",
			"funny",
		],
	},
	"cat-huh-cat-huh-etr.gif": {
		title: "Confused Cat Huh",
		tags: [
			"cat",
			"huh",
			"confused",
			"staring",
			"white cat",
			"oblivious",
			"what",
		],
	},
	"cat-no.gif": {
		title: "Cat Saying No",
		tags: [
			"cat",
			"no",
			"refusal",
			"staring",
			"wide eyes",
			"disagree",
			"rejection",
		],
	},
	"corgi-smirk.gif": {
		title: "Smirking Corgi",
		tags: [
			"corgi",
			"dog",
			"smirk",
			"smug",
			"side eye",
			"suspicious",
			"sly",
			"cheeky",
		],
	},
	"crying-happy.gif": {
		title: "Crying Wojak Happy Mask",
		tags: [
			"wojak",
			"crying",
			"mask",
			"fake smile",
			"hiding pain",
			"coping",
			"depressed",
			"pretending",
		],
	},
	"disappointed-fridge-guy.gif": {
		title: "Druski Rubbing Hands Together",
		tags: [
			"fridge",
			"disappointed",
			"black man",
			"sigh",
			"let down",
			"empty fridge",
			"hungry",
			"sad",
		],
	},
	"dog-smirk-dark-side.gif": {
		title: "Suspicious Dog Side Eye",
		tags: [
			"dog",
			"side eye",
			"squinting",
			"suspicious",
			"judgmental",
			"skeptical",
			"judging",
			"doubt",
		],
	},
	"dont-smile-dont-laugh.gif": {
		title: "Pablo Escobar Biting Lip",
		tags: [
			"man",
			"mustache",
			"biting lip",
			"trying not to laugh",
			"suppressing smile",
			"awkward",
			"holding back",
			"smirk",
		],
	},
	"druski-got-me.gif": {
		title: "Druski Laughing Hands Up",
		tags: [
			"druski",
			"black man",
			"hands up",
			"smiling",
			"defensive",
			"surrender",
			"innocent",
			"shrug",
		],
	},
	"druski-shrug-1.gif": {
		title: "Druski My Bad",
		tags: [
			"druski",
			"my bad",
			"hands up",
			"defensive",
			"apologetic",
			"shrugging",
			"mistake",
		],
	},
	"druski-shrug-hands-up-druski-shrug.gif": {
		title: "Druski Shrug With Stick",
		tags: [
			"druski",
			"american flag bandana",
			"holding stick",
			"shrugging",
			"confused",
			"hands out",
			"questioning",
		],
	},
	"druski-shrug.gif": {
		title: "Druski Saying I Tried",
		tags: [
			"druski",
			"i tried",
			"hands up",
			"defensive",
			"surrender",
			"shrugging",
			"giving up",
		],
	},
	"druski.gif": {
		title: "Druski What Do You Mean",
		tags: [
			"druski",
			"what do you mean by that",
			"squinting",
			"skeptical",
			"suspicious",
			"questioning",
			"confused",
		],
	},
	"fade-away-peace-out.gif": {
		title: "Disappearing Peace Out",
		tags: [
			"nileseyy niles",
			"peace out",
			"fading away",
			"disappearing",
			"peace sign",
			"leaving",
			"goodbye",
		],
	},
	"far-cry6-laugh.gif": {
		title: "Gus Fring Laughing Transition",
		tags: [
			"giancarlo esposito",
			"laughing then serious",
			"fake laugh",
			"sudden mood change",
			"deadpan stare",
			"intense",
			"not funny",
		],
	},
	"firat-roblox.gif": {
		title: "Steph Curry Space Shot",
		tags: [
			"stephen curry",
			"basketball",
			"shooting",
			"space",
			"moon",
			"earth",
			"absurd",
			"sports",
		],
	},
	"fly-insect.gif": {
		title: "Fly Rubbing Its Hands",
		tags: [
			"fly",
			"insect",
			"rubbing hands",
			"plotting",
			"scheming",
			"evil",
			"macro",
			"close up",
		],
	},
	"ford-and-ferrari-hats-off.gif": {
		title: "Enzo Ferrari Hats Off",
		tags: [
			"enzo ferrari",
			"ford v ferrari",
			"tipping hat",
			"respect",
			"acknowledgement",
			"suit",
			"sunglasses",
			"greeting",
		],
	},
	"freaky-sonic-sistertonin.gif": {
		title: "Sonic The Hedgehog Distressed",
		tags: [
			"sonic the hedgehog",
			"3d render",
			"creepy",
			"freaky",
			"holding head",
			"distressed",
			"cursed",
			"wide smile",
		],
	},
	"freaky-sonic-sonic-the-hedgehog.gif": {
		title: "Zesty Sonic Praying",
		tags: [
			"sonic the hedgehog",
			"3d render",
			"creepy",
			"freaky",
			"hands together",
			"sharp teeth",
			"plotting",
			"cursed",
		],
	},
	"ghee-khatam.gif": {
		title: "Rajkummar Rao Ghee Khatam",
		tags: [
			"rajkummar rao",
			"long hair",
			"beard",
			"ghee khatam",
			"staring",
			"blank stare",
			"exhausted",
			"disheveled",
		],
	},
	"go-do-it.gif": {
		title: "Jack Nicholson Do It",
		tags: [
			"jack nicholson",
			"grinning",
			"mischievous",
			"do it",
			"peer pressure",
			"encouragement",
			"movie scene",
		],
	},
	"gonna-touch-you-son.gif": {
		title: "Gonna Touch You Son",
		tags: [
			"threatening",
			"creepy",
			"im gonna touch you",
			"warning",
			"man",
			"text overlay",
			"predator",
		],
	},
	"goth-baddie-please.gif": {
		title: "Superbad One Freaky Goth",
		tags: [
			"superbad",
			"mclovin",
			"goth baddie",
			"movie cast",
			"request",
			"ordering",
			"awkward",
		],
	},
	"hamster-cute.gif": {
		title: "Hamster Looking Around Confused",
		tags: [
			"hamster",
			"cute",
			"blanket",
			"cozy",
			"curious",
			"animal",
			"pet",
		],
	},
	"happy-cat.gif": {
		title: "Close Up Smiling Cat",
		tags: [
			"cat",
			"smiling",
			"happy",
			"whiskers",
			"cute",
			"close up",
			"content",
		],
	},
	"heh-huh.gif": {
		title: "Snowball Rabbit Heh Expression",
		tags: [
			"rabbit",
			"snowball",
			"secret life of pets",
			"heh",
			"confused",
			"skeptical",
			"questioning",
			"animated",
		],
	},
	"help.gif": {
		title: "Shocked Dog Looking At Phone",
		tags: [
			"dog",
			"smartphone",
			"shocked",
			"wide eyes",
			"staring",
			"disbelief",
			"screen",
			"scared",
		],
	},
	"high-five-walter-white.gif": {
		title: "Walter White Jesse Pinkman High Five",
		tags: [
			"breaking bad",
			"jesse pinkman",
			"walter white",
			"lab",
			"yelling",
			"celebration",
			"excitement",
			"science",
		],
	},
	"hooray-letsgo.gif": {
		title: "Baby Cheering Lets Go",
		tags: [
			"kid",
			"lets go",
			"yelling",
			"excited",
			"hype",
			"celebration",
			"win",
			"fan",
		],
	},
	"huh-cat.gif": {
		title: "Tired Orange Cat",
		tags: [
			"orange cat",
			"sleepy",
			"high",
			"chill",
			"staring",
			"tired",
			"dazed",
			"expressionless",
		],
	},
	"i-got-you.gif": {
		title: "Happy Laughing Baby",
		tags: [
			"baby",
			"laughing",
			"happy",
			"joy",
			"hysterical",
			"giggling",
			"funny",
			"toddler",
		],
	},
	"i-know-but-i-cant-proof.gif": {
		title: "Nollywood Men Intense Confrontation",
		tags: [
			"men",
			"staring",
			"suspicious",
			"confrontation",
			"intense",
			"drama",
			"serious",
			"side eye",
		],
	},
	"i-use-ai.gif": {
		title: "No Thanks I Use AI",
		tags: [
			"no thanks",
			"i use ai",
			"brain",
			"artificial intelligence",
			"stop gesture",
			"rejection",
			"tech bro",
			"automation",
		],
	},
	"it-shouldve-been-me-not-him.gif": {
		title: "Yami Yugi Jealous Outcry",
		tags: [
			"yugioh",
			"screaming",
			"jealousy",
			"unfair",
			"regret",
			"it should have been me",
			"anime yelling",
			"envy",
		],
	},
	"its-me.gif": {
		title: "Obi-Wan He's Me",
		tags: [
			"star wars",
			"obi wan kenobi",
			"of course i know him",
			"hes me",
			"realization",
			"desert",
			"self awareness",
			"identity",
		],
	},
	"its-time-to-stop.gif": {
		title: "Shaq Time Out Gesture",
		tags: [
			"shaq",
			"timeout",
			"stop",
			"pause",
			"shaquille oneal",
			"hand gesture",
			"wait a minute",
			"basketball",
		],
	},
	"james-doakes-dexter-dexter.gif": {
		title: "DMX Driving Intensely",
		tags: [
			"driving",
			"staring",
			"car interior",
			"serious face",
			"focused",
			"night drive",
			"windshield",
			"staring ahead",
		],
	},
	"james-harden-bye.gif": {
		title: "James Harden Side Eye",
		tags: [
			"james harden",
			"side eye",
			"confusion",
			"walking away",
			"nba",
			"interview",
			"disbelief",
			"basketball",
		],
	},
	"jumping-hopping.gif": {
		title: "Dog Falls Into Box",
		tags: [
			"black dog",
			"french bulldog",
			"cardboard boxes",
			"climbing",
			"falling",
			"puppy fail",
			"clumsy animal",
			"stuck",
		],
	},
	"kanye-laugh.gif": {
		title: "Kanye Kidding Not Kidding",
		tags: [
			"kanye west",
			"kidding not kidding",
			"laughing",
			"sudden serious",
			"mood shift",
			"celebrity reaction",
			"deadpan",
			"sarcastic",
		],
	},
	"kanye-waste.gif": {
		title: "Kanye West Mood Shift",
		tags: [
			"kanye west",
			"smiling",
			"instant serious",
			"mood change",
			"fake smile",
			"stone faced",
			"rapper reaction",
			"realization",
		],
	},
	"ketartine-ragondin.gif": {
		title: "Screaming Marmot",
		tags: [
			"screaming marmot",
			"groundhog",
			"mountain background",
			"yelling",
			"internal scream",
			"loud noise",
			"nature meme",
			"shouting",
		],
	},
	"kétartine-ragondin.gif": {
		title: "Screaming Marmot",
		tags: [
			"screaming marmot",
			"yelling animal",
			"high pitched",
			"funny scream",
			"wood railing",
			"shock",
			"surprise",
			"distress",
		],
	},
	"kmt-yeah.gif": {
		title: "Bearded Man Pouting Face",
		tags: [
			"zesty face",
			"bald man",
			"bearded guy",
			"pursed lips",
			"duck face",
			"flirty look",
			"funny expression",
			"pouty",
		],
	},
	"laughing-then-serious-laughing-then-stoned.gif": {
		title: "xQc Laughing Transition",
		tags: ["xqc", "smiling", "serious", "deadpan", "transition", "stream"],
	},
	"lil-dihh.gif": {
		title: "Sackboy Big Dreams",
		tags: [
			"sackboy",
			"littlebigplanet",
			"lil dihh big dreams",
			"window",
			"staring",
			"looking out",
		],
	},
	"made-it-to-friday.gif": {
		title: "Nick Wilde Happy Friday",
		tags: [
			"zootopia",
			"nick wilde",
			"fox",
			"made it",
			"happy friday",
			"dancing",
		],
	},
	"mario-goth.gif": {
		title: "Mario and Goth Girl",
		tags: [
			"mario",
			"nintendo",
			"goth girl",
			"sitting",
			"looking",
			"crossover",
		],
	},
	"middle-finger-f-u.gif": {
		title: "Walter White Middle Finger",
		tags: [
			"walter white",
			"breaking bad",
			"middle finger",
			"flipping off",
			"looking up",
			"angry",
		],
	},
	"money.gif": {
		title: "Vince McMahon Smelling Money",
		tags: [
			"vince mcmahon",
			"wwe",
			"smelling money",
			"stack of cash",
			"rich",
			"greedy",
		],
	},
	"mr-least.webp": {
		title: "Mr Least",
		tags: [
			"man",
			"smiling",
			"staring",
			"creepy",
			"tiktok comment",
			"awkward",
			"uncomfortable",
		],
	},
	"noot-noot-dark.gif": {
		title: "Sad Pingu Crying",
		tags: [
			"pingu",
			"penguin",
			"scared",
			"traumatized",
			"staring",
			"dark",
			"noot noot",
		],
	},
	"nope.gif": {
		title: "Shannon Sharpe Skeptical Face",
		tags: [
			"shannon sharpe",
			"smug",
			"suit",
			"pursed lips",
			"arrogant",
			"sports desk",
			"holding laugh",
		],
	},
	"nub-cat-ohh-i-understand-it-now.gif": {
		title: "Cat Phone Old Man",
		tags: [
			"blue cat",
			"phone",
			"reading",
			"shocked",
			"shadowed face",
			"disappointed",
			"regret",
		],
	},
	"nub-cat-uee-aa-u-ee-aa.gif": {
		title: "Nub Cat Loaf Views",
		tags: [
			"blue cat",
			"loaf",
			"blob",
			"cute",
			"resting",
			"x butt",
			"squished",
		],
	},
	"nub-cat-unzips.gif": {
		title: "Nub Cat Unzips Pants",
		tags: [
			"blue cat",
			"sitting",
			"desk",
			"unzips",
			"sus",
			"inappropriate",
			"looking down",
		],
	},
	"nub-nub-cat-11.gif": {
		title: "Nub Cat Blushing Face",
		tags: [
			"blue cat",
			"blushing",
			"shy reaction",
			"embarrassed face",
			"cute kitten",
			"pink cheeks",
			"bashful expression",
			"flustered",
		],
	},
	"nub-nub-cat-12.gif": {
		title: "Nub Cat Peeking Out",
		tags: [
			"blue cat",
			"peeking",
			"staring",
			"watching you",
			"curious kitten",
			"looking over",
			"silent judgment",
			"observant",
		],
	},
	"nub-nub-cat-13.gif": {
		title: "Nub Cat Pointing Up",
		tags: [
			"blue cat",
			"pointing finger",
			"actually meme",
			"smug face",
			"correction gesture",
			"lecturing",
			"confident kitten",
			"finger wag",
		],
	},
	"nub-nub-cat-14.gif": {
		title: "Blue Cat Demanding Kiss",
		tags: [
			"blue cat",
			"holding sword",
			"i wam kiss",
			"angry blushing",
			"aggressive affection",
			"demanding love",
			"funny caption",
			"tsundere cat",
		],
	},
	"nub-nub-cat-15.gif": {
		title: "Blue Cat Licking Moon",
		tags: [
			"blue cat",
			"licking",
			"tongue out",
			"tasting",
			"eyes closed",
			"sensory reaction",
			"mlem",
			"funny kitten",
		],
	},
	"nub-nub-cat-16.gif": {
		title: "Sad Cat Under Arrest",
		tags: [
			"blue cat",
			"handcuffed",
			"stole my heart",
			"ur under arrest",
			"big watery eyes",
			"love confession",
			"flirty pickup line",
			"pleading face",
		],
	},
	"nub-nub-cat-17.gif": {
		title: "Hand Grabbing Blue Cat",
		tags: [
			"nub cat",
			"blue cat",
			"held in hand",
			"squished face",
			"blank expression",
			"staring",
			"small cat",
			"pick up",
		],
	},
	"nub-nub-cat-18.gif": {
		title: "Buff Cats Red Room",
		tags: [
			"muscular cats",
			"buff cats",
			"standing in cave",
			"back view",
			"red background",
			"strength",
			"dominance",
			"gigachad",
		],
	},
	"nub-nub-cat-19.gif": {
		title: "Blue Cat Holding Flower",
		tags: [
			"nub cat",
			"blue cat",
			"giving rose",
			"happy cat",
			"pink flower",
			"offering",
			"wholesome",
			"sharing",
		],
	},
	"nub-nub-cat-2.gif": {
		title: "Laughing To Depressed Cat",
		tags: [
			"blue cat",
			"laughing then serious",
			"mood swing",
			"depressed cat",
			"realization",
			"darkness",
			"fake happy",
			"exhaustion",
		],
	},
	"nub-nub-cat-4.gif": {
		title: "Playful Threat Blue Cat",
		tags: [
			"blue cat",
			"pink bow",
			"im gonna touch u",
			"threatening",
			"silly cat",
			"staring eyes",
			"pink background",
			"creepy cute",
		],
	},
	"nub-nub-cat-6.gif": {
		title: "Skeptical Blue Cat Gamer",
		tags: [
			"blue cat",
			"gaming",
			"holding controller",
			"suspicious look",
			"side eye",
			"judgmental",
			"skeptical",
			"concentrating",
		],
	},
	"nub-nub-cat-7.gif": {
		title: "Thinking Of You Cat",
		tags: [
			"white cat",
			"blushing",
			"thinking of you rn",
			"love",
			"sweet",
			"wholesome",
			"cute cat",
			"affection",
		],
	},
	"nub-nub-cat-8.gif": {
		title: "Heartfelt Blue Nub Cat",
		tags: [
			"blue cat",
			"i want you",
			"hearts background",
			"blushing cat",
			"crush",
			"romantic intent",
			"clingy",
			"obsessed",
		],
	},
	"nub-nub-cat-9.gif": {
		title: "Reaching Out Blue Cat",
		tags: [
			"blue cat",
			"wide open mouth",
			"67 number",
			"shocked",
			"confused",
			"distorted paws",
			"cursed cat",
			"weird expression",
		],
	},
	"nub-nub-cat-flashbang.gif": {
		title: "Bugcat Blasted By Light",
		tags: [
			"cat in bed",
			"phone screen glow",
			"scrolling at night",
			"insomnia",
			"bright light",
			"blinded",
			"night owl",
			"relatable",
		],
	},
	"nub-nub-cat.gif": {
		title: "LeBron James Cat Morph",
		tags: [
			"lebron james face",
			"cat body",
			"silhouette transition",
			"lebron cat",
			"funny edit",
			"celebrity cat",
			"smiling lebron",
			"weird meme",
		],
	},
	"nubcat-iwanttocatyou-1.gif": {
		title: "Happy Bugcat Dancing",
		tags: [
			"blue cat",
			"cheering",
			"celebration",
			"happy cat",
			"raised paws",
			"excited",
			"victory",
			"yay",
		],
	},
	"nubcat-iwanttocatyou.gif": {
		title: "Bugcat Rubbing Tired Eyes",
		tags: [
			"blue cat",
			"cartoon",
			"pinching fingers",
			"tiny amount",
			"squinting",
			"skeptical",
			"examining",
		],
	},
	"oh-yeah-sameer.gif": {
		title: "Sameer Oh Yeah",
		tags: [
			"man",
			"sunglasses",
			"ponytail",
			"oh yeah text",
			"looking up",
			"realization",
			"excited",
		],
	},
	"oh-yeah.gif": {
		title: "Chris Pratt Shocked Face",
		tags: [
			"chris pratt",
			"andy dwyer",
			"parks and recreation",
			"surprised",
			"shocked",
			"mouth open",
			"excited",
		],
	},
	"peace-out-im-out.gif": {
		title: "Otter Saying Peace Out",
		tags: [
			"animal",
			"ferret",
			"possum",
			"peace out text",
			"peace sign",
			"leaving",
			"goodbye",
		],
	},
	"peace-out-peace-sign.gif": {
		title: "Otter Giving Peace Sign",
		tags: [
			"animal",
			"ferret",
			"possum",
			"peace sign",
			"leaving",
			"goodbye",
			"disappearing",
		],
	},
	"peace-out.gif": {
		title: "Man Fading Away Peace",
		tags: [
			"nileseyy niles",
			"black man",
			"peace sign",
			"fading away",
			"disappearing",
			"leaving",
			"goodbye",
		],
	},
	"pedro-pascal-1.gif": {
		title: "Pedro Pascal Laughing Crying",
		tags: [
			"pedro pascal",
			"laughing crying",
			"uncontrollable laughter",
			"emotional roller coaster",
			"funny but sad",
			"hysterical",
			"switch",
			"laughing then crying",
		],
	},
	"pedro-pascal.gif": {
		title: "Pedro Pascal Smirking Smile",
		tags: [
			"pedro pascal",
			"smiling",
			"creepy smile",
			"awkward grin",
			"looking away",
			"hiding pain",
			"staring",
			"fake happy",
		],
	},
	"pentol-stiker-pentol.gif": {
		title: "Pentol Typing On Laptop",
		tags: [
			"white blob",
			"character",
			"typing laptop",
			"concentrating",
			"working hard",
			"blushing",
			"gaming",
			"determined",
		],
	},
	"rolando-ronaldo.gif": {
		title: "Cristiano Ronaldo Sipping Drink",
		tags: [
			"cristiano ronaldo",
			"drinking glass",
			"winking",
			"smooth",
			"celebrity",
			"sipping",
			"charming",
			"confident",
		],
	},
	"sarcastic-clap.gif": {
		title: "Ken Doll Slow Clap",
		tags: [
			"doll puppet",
			"slow clap",
			"sarcastic",
			"creepy",
			"unimpressed",
			"staring",
			"clapping",
			"judgmental",
		],
	},
	"shannon-sharpe-suit-meme.gif": {
		title: "Shannon Sharpe Sharp Suits",
		tags: [
			"shannon sharpe",
			"suit and tie",
			"sharp dressed",
			"entrance",
			"flexing",
			"fashionable",
			"confident walk",
			"well dressed",
		],
	},
	"shaq-shimmy.gif": {
		title: "Shaq Smirking In Red",
		tags: [
			"shaq",
			"shaquille o'neal",
			"shimmy",
			"smirk",
			"shoulder shake",
			"flirtatious",
			"red shirt",
			"suggestive",
		],
	},
	"shock-wtf-joe-coin-emotiguy-stare-serious-disgust-dark.gif": {
		title: "Dramatic Emoji Reaching Out",
		tags: [
			"mike wazowski",
			"one eye",
			"stare",
			"disgust",
			"dark",
			"serious",
			"creepy",
			"judgemental",
		],
	},
	"shocked-ishowspeed.gif": {
		title: "IShowSpeed Shocked At Event",
		tags: [
			"ishowspeed",
			"speed",
			"shocked",
			"screaming",
			"theater",
			"surprised",
			"overwhelmed",
			"wide mouth",
		],
	},
	"shocked-surprised-1.gif": {
		title: "Shocked Cat What",
		tags: [
			"cat",
			"shocked",
			"wide eyes",
			"what",
			"disbelief",
			"mouth open",
			"stunned",
			"feline",
		],
	},
	"shocked-surprised.gif": {
		title: "Drew Scanlon Wait What",
		tags: [
			"blinking guy",
			"drew scanlon",
			"sunglasses",
			"wait what",
			"confusion",
			"double take",
			"disbelief",
			"realization",
		],
	},
	"silly-nub-cat-mommy.gif": {
		title: "Blushing Capoo Cat Mommy",
		tags: [
			"blue cat",
			"mommy",
			"blushing",
			"shy",
			"submissive",
			"finger touch",
			"anime style",
			"embarrassed",
		],
	},
	"sillynubcat-nubcat.gif": {
		title: "Capoo Cat Drawing",
		tags: [
			"blue creature",
			"writing",
			"drawing",
			"notes",
			"study",
			"homework",
			"pencil",
			"focused",
		],
	},
	"small-dihh.gif": {
		title: "Small Dih Big Dreams",
		tags: [
			"man in suit",
			"cityscape",
			"ambition",
			"dreams",
			"motivational",
			"success",
			"sunset",
			"business",
		],
	},
	"sonic-zesty.gif": {
		title: "Creepy Sonic Expressions",
		tags: [
			"sonic",
			"clapping",
			"laughing",
			"praying",
			"expressions",
			"3d render",
			"sassy",
			"dramatic",
		],
	},
	"spit-in-mouth.webp": {
		title: "Spit In Mouth",
		tags: [
			"anime woman",
			"side eye",
			"suspicious",
			"skeptical",
			"judging",
			"look back",
			"wavy hair",
			"distrust",
		],
	},
	"squinting-skeptical.gif": {
		title: "Fry Squinting Suspiciously",
		tags: [
			"fry",
			"squinting",
			"suspicious",
			"skepticism",
			"investigating",
			"unsure",
			"zoom in",
			"disbelief",
		],
	},
	"stan-twt-evil-chihuahua-1.gif": {
		title: "Chihuahua Grinning With Teeth",
		tags: [
			"chihuahua",
			"creepy smile",
			"wide eyes",
			"unsettling",
			"suspicious",
			"weird dog",
			"grin",
			"intense",
		],
	},
	"stan-twt-evil-chihuahua.gif": {
		title: "Michael Jordan Get Help",
		tags: [
			"chihuahua",
			"dog",
			"side eye",
			"awkward smile",
			"suspicious",
			"guilty",
			"showing teeth",
			"knowing smile",
		],
	},
	"stop-it-stop.gif": {
		title: "Confused Fluffy Dog",
		tags: [
			"michael jordan",
			"stop it",
			"get some help",
			"disapproval",
			"intervention",
			"serious",
			"cringe",
		],
	},
	"strange-statement.gif": {
		title: "Excited Boy Clapping Hands",
		tags: [
			"fluffy dog",
			"strange statement",
			"confused",
			"blank stare",
			"silent judgment",
			"gang confused",
			"wtf",
		],
	},
	"suenitosgifs-nollywood-roll.gif": {
		title: "Excited Boy Clapping Hands",
		tags: [
			"osita iheme",
			"boy",
			"clapping",
			"here we go",
			"excited",
			"anticipation",
			"drama",
			"ready",
		],
	},
	"suenitosgifs-traumatized-mr-incredible.gif": {
		title: "Mr Incredible Becoming Uncanny",
		tags: [
			"mr incredible",
			"traumatized",
			"black and white",
			"those who know",
			"dark realization",
			"despair",
			"uncanny",
			"horror",
		],
	},
	"sure-oh-ok.gif": {
		title: "Kermit Drinking Tea Sarcastic",
		tags: [
			"kermit the frog",
			"sipping tea",
			"if you say so",
			"sarcastic",
			"skeptical",
			"none of my business",
			"drinking",
		],
	},
	"sure.gif": {
		title: "Skeptical Cat Saying Sure",
		tags: [
			"cat",
			"squinting",
			"sure",
			"doubtful",
			"skeptical",
			"suspicious",
			"unconvinced",
		],
	},
	"suspicious-eyes.gif": {
		title: "Hei Hei Chicken Expressions",
		tags: [
			"heihei",
			"chicken",
			"moana",
			"staring",
			"clueless",
			"blinking",
			"confused",
			"blank stare",
		],
	},
	"sussy-cant-prove-it.gif": {
		title: "Uncle Phil Watching You",
		tags: [
			"tyrese gibson",
			"fast and furious",
			"eyes on you",
			"watching you",
			"pointing",
			"two fingers",
			"warning",
		],
	},
	"taking-notes.gif": {
		title: "Man Writing In Notebook",
		tags: [
			"taking notes",
			"writing",
			"notebook",
			"looking up",
			"pause",
			"realization",
			"black hoodie",
			"hold up",
		],
	},
	"thumbs-up-hamster-cute.gif": {
		title: "Hamster Giving Thumbs Up",
		tags: [
			"hamster",
			"thumbs up",
			"approval",
			"cute animal",
			"positive vibes",
			"agreement",
			"good job",
		],
	},
	"type-c.jpg": {
		title: "Type C",
		tags: [
			"man in turban",
			"punjabi",
			"sikh",
			"c-type charger",
			"judgmental",
			"serious face",
			"phone humor",
		],
	},
	"up-is-not-jump-knee.gif": {
		title: "Man Sawing Plastic Leg",
		tags: [
			"sawing",
			"mannequin leg",
			"kitchen",
			"bizarre",
			"weird diy",
			"strange action",
			"focused expression",
		],
	},
	"viagra.gif": {
		title: "Cyanide And Happiness Line",
		tags: [
			"stick figure",
			"hotdog stand",
			"cyanide and happiness",
			"giant sausage",
			"line cutter",
			"pushing",
			"rude behavior",
			"cartoon slap",
		],
	},
	"what-you-sure.gif": {
		title: "Suspicious Side Eye Dog",
		tags: [
			"dachshund",
			"suspicious dog",
			"side eye",
			"skeptical",
			"judgmental look",
			"brown dog",
			"not amused",
		],
	},
	"yellow-emoji-no-no-emotiguy.gif": {
		title: "Angry Emoji Pointing Up",
		tags: [
			"yellow emoji",
			"angry face",
			"pointing up",
			"3d character",
			"lecturing",
			"annoyed",
			"actually",
			"tough guy stance",
		],
	},
	"youre-joddamn-right-jod.gif": {
		title: "Walter White Goddamn Right",
		tags: [
			"walter white",
			"breaking bad",
			"you're goddamn right",
			"joddamn",
			"heisenberg",
			"glasses",
			"goattee",
			"agreement",
		],
	},
}
