export const TAGS_DATABASE: Record<string, string[]> = {
	"achha.webp": [
		"achha lode",
		"sarcastic doraemon",
		"sarcastic",
		"doraemon",
		"nobita",
		"indian",
		"hindi",
	],
	"anya-forger.gif": [
		"anya forger",
		"spy x family",
		"smug grin",
		"heh",
		"scheming",
		"knowing look",
		"satisfied",
		"anime reaction",
	],
	"baby-laugh-ai-baby.gif": [
		"laughing baby",
		"giggling baby",
		"happy baby",
		"cute",
		"wholesome",
		"amused",
		"infant laugh",
	],
	"bamboozled-astonished.gif": [
		"astonished",
		"wide eyes",
		"staring",
		"shock",
		"disbelief",
		"bamboozled",
		"wtf",
		"what",
	],
	"betrayal-phone.gif": [
		"blue cat",
		"phone",
		"checking phone",
		"bad news",
		"betrayal",
		"traumatized",
		"realization",
		"shocking news",
	],
	"blinking-eyes-white-guy.gif": [
		"drew scanlon",
		"blinking guy",
		"blinking",
		"confused",
		"disbelief",
		"double take",
		"processing",
		"awkward",
	],
	"blush.gif": [
		"blushing",
		"texting",
		"in bed",
		"phone",
		"crush",
		"staring",
		"wholesome",
	],
	"bobawooyo-dog-confused.gif": [
		"dog",
		"wait what",
		"shocked",
		"surprised",
		"confused",
		"astonished",
		"bewildered",
	],
	"bund-mraa.png": [
		"punjabi",
		"pointing",
		"field",
		"insult",
		"aggressive",
		"go away",
		"sukhbir singh badal",
	],
	"cast-net-fishing-fall.gif": [
		"fishing",
		"fail",
		"boat",
		"falling",
		"water",
		"net",
		"accident",
		"funny",
	],
	"cat-huh-cat-huh-etr.gif": [
		"cat",
		"huh",
		"confused",
		"staring",
		"white cat",
		"oblivious",
		"what",
	],
	"cat-no.gif": [
		"cat",
		"no",
		"refusal",
		"staring",
		"wide eyes",
		"disagree",
		"rejection",
	],
	"corgi-smirk.gif": [
		"corgi",
		"dog",
		"smirk",
		"smug",
		"side eye",
		"suspicious",
		"sly",
		"cheeky",
	],
	"crying-happy.gif": [
		"wojak",
		"crying",
		"mask",
		"fake smile",
		"hiding pain",
		"coping",
		"depressed",
		"pretending",
	],
	"disappointed-fridge-guy.gif": [
		"fridge",
		"disappointed",
		"black man",
		"sigh",
		"let down",
		"empty fridge",
		"hungry",
		"sad",
	],
	"dog-smirk-dark-side.gif": [
		"dog",
		"side eye",
		"squinting",
		"suspicious",
		"judgmental",
		"skeptical",
		"judging",
		"doubt",
	],
	"dont-smile-dont-laugh.gif": [
		"man",
		"mustache",
		"biting lip",
		"trying not to laugh",
		"suppressing smile",
		"awkward",
		"holding back",
		"smirk",
	],
	"druski-got-me.gif": [
		"druski",
		"black man",
		"hands up",
		"smiling",
		"defensive",
		"surrender",
		"innocent",
		"shrug",
	],
	"druski-shrug-1.gif": [
		"druski",
		"my bad",
		"hands up",
		"defensive",
		"apologetic",
		"shrugging",
		"mistake",
	],
	"druski-shrug-hands-up-druski-shrug.gif": [
		"druski",
		"american flag bandana",
		"holding stick",
		"shrugging",
		"confused",
		"hands out",
		"questioning",
	],
	"druski-shrug.gif": [
		"druski",
		"i tried",
		"hands up",
		"defensive",
		"surrender",
		"shrugging",
		"giving up",
	],
	"druski.gif": [
		"druski",
		"what do you mean by that",
		"squinting",
		"skeptical",
		"suspicious",
		"questioning",
		"confused",
	],
	"fade-away-peace-out.gif": [
		"nileseyy niles",
		"peace out",
		"fading away",
		"disappearing",
		"peace sign",
		"leaving",
		"goodbye",
	],
	"far-cry6-laugh.gif": [
		"giancarlo esposito",
		"laughing then serious",
		"fake laugh",
		"sudden mood change",
		"deadpan stare",
		"intense",
		"not funny",
	],
	"firat-roblox.gif": [
		"stephen curry",
		"basketball",
		"shooting",
		"space",
		"moon",
		"earth",
		"absurd",
		"sports",
	],
	"fly-insect.gif": [
		"fly",
		"insect",
		"rubbing hands",
		"plotting",
		"scheming",
		"evil",
		"macro",
		"close up",
	],
	"ford-and-ferrari-hats-off.gif": [
		"enzo ferrari",
		"ford v ferrari",
		"tipping hat",
		"respect",
		"acknowledgement",
		"suit",
		"sunglasses",
		"greeting",
	],
	"freaky-sonic-sistertonin.gif": [
		"sonic the hedgehog",
		"3d render",
		"creepy",
		"freaky",
		"holding head",
		"distressed",
		"cursed",
		"wide smile",
	],
	"freaky-sonic-sonic-the-hedgehog.gif": [
		"sonic the hedgehog",
		"3d render",
		"creepy",
		"freaky",
		"hands together",
		"sharp teeth",
		"plotting",
		"cursed",
	],
	"ghee-khatam.gif": [
		"rajkummar rao",
		"long hair",
		"beard",
		"ghee khatam",
		"staring",
		"blank stare",
		"exhausted",
		"disheveled",
	],
	"go-do-it.gif": [
		"jack nicholson",
		"grinning",
		"mischievous",
		"do it",
		"peer pressure",
		"encouragement",
		"movie scene",
	],
	"gonna-touch-you-son.gif": [
		"threatening",
		"creepy",
		"im gonna touch you",
		"warning",
		"man",
		"text overlay",
		"predator",
	],
	"goth-baddie-please.gif": [
		"superbad",
		"mclovin",
		"goth baddie",
		"movie cast",
		"request",
		"ordering",
		"awkward",
	],
	"hamster-cute.gif": [
		"hamster",
		"cute",
		"blanket",
		"cozy",
		"curious",
		"animal",
		"pet",
	],
	"happy-cat.gif": [
		"cat",
		"smiling",
		"happy",
		"whiskers",
		"cute",
		"close up",
		"content",
	],
	"heh-huh.gif": [
		"rabbit",
		"snowball",
		"secret life of pets",
		"heh",
		"confused",
		"skeptical",
		"questioning",
		"animated",
	],
	"help.gif": [
		"dog",
		"smartphone",
		"shocked",
		"wide eyes",
		"staring",
		"disbelief",
		"screen",
		"scared",
	],
	"high-five-walter-white.gif": [
		"breaking bad",
		"jesse pinkman",
		"walter white",
		"lab",
		"yelling",
		"celebration",
		"excitement",
		"science",
	],
	"hooray-letsgo.gif": [
		"kid",
		"lets go",
		"yelling",
		"excited",
		"hype",
		"celebration",
		"win",
		"fan",
	],
	"huh-cat.gif": [
		"orange cat",
		"sleepy",
		"high",
		"chill",
		"staring",
		"tired",
		"dazed",
		"expressionless",
	],
	"i-got-you.gif": [
		"baby",
		"laughing",
		"happy",
		"joy",
		"hysterical",
		"giggling",
		"funny",
		"toddler",
	],
	"i-know-but-i-cant-proof.gif": [
		"men",
		"staring",
		"suspicious",
		"confrontation",
		"intense",
		"drama",
		"serious",
		"side eye",
	],
	"i-use-ai.gif": [
		"no thanks",
		"i use ai",
		"brain",
		"artificial intelligence",
		"stop gesture",
		"rejection",
		"tech bro",
		"automation",
	],
	"it-shouldve-been-me-not-him.gif": [
		"yugioh",
		"screaming",
		"jealousy",
		"unfair",
		"regret",
		"it should have been me",
		"anime yelling",
		"envy",
	],
	"its-me.gif": [
		"star wars",
		"obi wan kenobi",
		"of course i know him",
		"hes me",
		"realization",
		"desert",
		"self awareness",
		"identity",
	],
	"its-time-to-stop.gif": [
		"shaq",
		"timeout",
		"stop",
		"pause",
		"shaquille oneal",
		"hand gesture",
		"wait a minute",
		"basketball",
	],
	"james-doakes-dexter-dexter.gif": [
		"driving",
		"staring",
		"car interior",
		"serious face",
		"focused",
		"night drive",
		"windshield",
		"staring ahead",
	],
	"james-harden-bye.gif": [
		"james harden",
		"side eye",
		"confusion",
		"walking away",
		"nba",
		"interview",
		"disbelief",
		"basketball",
	],
	"jumping-hopping.gif": [
		"black dog",
		"french bulldog",
		"cardboard boxes",
		"climbing",
		"falling",
		"puppy fail",
		"clumsy animal",
		"stuck",
	],
	"kanye-laugh.gif": [
		"kanye west",
		"kidding not kidding",
		"laughing",
		"sudden serious",
		"mood shift",
		"celebrity reaction",
		"deadpan",
		"sarcastic",
	],
	"kanye-waste.gif": [
		"kanye west",
		"smiling",
		"instant serious",
		"mood change",
		"fake smile",
		"stone faced",
		"rapper reaction",
		"realization",
	],
	"ketartine-ragondin.gif": [
		"screaming marmot",
		"groundhog",
		"mountain background",
		"yelling",
		"internal scream",
		"loud noise",
		"nature meme",
		"shouting",
	],
	"kétartine-ragondin.gif": [
		"screaming marmot",
		"yelling animal",
		"high pitched",
		"funny scream",
		"wood railing",
		"shock",
		"surprise",
		"distress",
	],
	"kmt-yeah.gif": [
		"zesty face",
		"bald man",
		"bearded guy",
		"pursed lips",
		"duck face",
		"flirty look",
		"funny expression",
		"pouty",
	],
	"laughing-then-serious-laughing-then-stoned.gif": [
		"xqc",
		"smiling",
		"serious",
		"deadpan",
		"transition",
		"stream",
	],
	"lil-dihh.gif": [
		"sackboy",
		"littlebigplanet",
		"lil dihh big dreams",
		"window",
		"staring",
		"looking out",
	],
	"made-it-to-friday.gif": [
		"zootopia",
		"nick wilde",
		"fox",
		"made it",
		"happy friday",
		"dancing",
	],
	"mario-goth.gif": [
		"mario",
		"nintendo",
		"goth girl",
		"sitting",
		"looking",
		"crossover",
	],
	"middle-finger-f-u.gif": [
		"walter white",
		"breaking bad",
		"middle finger",
		"flipping off",
		"looking up",
		"angry",
	],
	"money.gif": [
		"vince mcmahon",
		"wwe",
		"smelling money",
		"stack of cash",
		"rich",
		"greedy",
	],
	"mr-least.webp": [
		"man",
		"smiling",
		"staring",
		"creepy",
		"tiktok comment",
		"awkward",
		"uncomfortable",
	],
	"noot-noot-dark.gif": [
		"pingu",
		"penguin",
		"scared",
		"traumatized",
		"staring",
		"dark",
		"noot noot",
	],
	"nope.gif": [
		"shannon sharpe",
		"smug",
		"suit",
		"pursed lips",
		"arrogant",
		"sports desk",
		"holding laugh",
	],
	"nub-cat-ohh-i-understand-it-now.gif": [
		"blue cat",
		"phone",
		"reading",
		"shocked",
		"shadowed face",
		"disappointed",
		"regret",
	],
	"nub-cat-uee-aa-u-ee-aa.gif": [
		"blue cat",
		"loaf",
		"blob",
		"cute",
		"resting",
		"x butt",
		"squished",
	],
	"nub-cat-unzips.gif": [
		"blue cat",
		"sitting",
		"desk",
		"unzips",
		"sus",
		"inappropriate",
		"looking down",
	],
	"nub-nub-cat-11.gif": [
		"blue cat",
		"blushing",
		"shy reaction",
		"embarrassed face",
		"cute kitten",
		"pink cheeks",
		"bashful expression",
		"flustered",
	],
	"nub-nub-cat-12.gif": [
		"blue cat",
		"peeking",
		"staring",
		"watching you",
		"curious kitten",
		"looking over",
		"silent judgment",
		"observant",
	],
	"nub-nub-cat-13.gif": [
		"blue cat",
		"pointing finger",
		"actually meme",
		"smug face",
		"correction gesture",
		"lecturing",
		"confident kitten",
		"finger wag",
	],
	"nub-nub-cat-14.gif": [
		"blue cat",
		"holding sword",
		"i wam kiss",
		"angry blushing",
		"aggressive affection",
		"demanding love",
		"funny caption",
		"tsundere cat",
	],
	"nub-nub-cat-15.gif": [
		"blue cat",
		"licking",
		"tongue out",
		"tasting",
		"eyes closed",
		"sensory reaction",
		"mlem",
		"funny kitten",
	],
	"nub-nub-cat-16.gif": [
		"blue cat",
		"handcuffed",
		"stole my heart",
		"ur under arrest",
		"big watery eyes",
		"love confession",
		"flirty pickup line",
		"pleading face",
	],
	"nub-nub-cat-17.gif": [
		"nub cat",
		"blue cat",
		"held in hand",
		"squished face",
		"blank expression",
		"staring",
		"small cat",
		"pick up",
	],
	"nub-nub-cat-18.gif": [
		"muscular cats",
		"buff cats",
		"standing in cave",
		"back view",
		"red background",
		"strength",
		"dominance",
		"gigachad",
	],
	"nub-nub-cat-19.gif": [
		"nub cat",
		"blue cat",
		"giving rose",
		"happy cat",
		"pink flower",
		"offering",
		"wholesome",
		"sharing",
	],
	"nub-nub-cat-2.gif": [
		"blue cat",
		"laughing then serious",
		"mood swing",
		"depressed cat",
		"realization",
		"darkness",
		"fake happy",
		"exhaustion",
	],
	"nub-nub-cat-4.gif": [
		"blue cat",
		"pink bow",
		"im gonna touch u",
		"threatening",
		"silly cat",
		"staring eyes",
		"pink background",
		"creepy cute",
	],
	"nub-nub-cat-6.gif": [
		"blue cat",
		"gaming",
		"holding controller",
		"suspicious look",
		"side eye",
		"judgmental",
		"skeptical",
		"concentrating",
	],
	"nub-nub-cat-7.gif": [
		"white cat",
		"blushing",
		"thinking of you rn",
		"love",
		"sweet",
		"wholesome",
		"cute cat",
		"affection",
	],
	"nub-nub-cat-8.gif": [
		"blue cat",
		"i want you",
		"hearts background",
		"blushing cat",
		"crush",
		"romantic intent",
		"clingy",
		"obsessed",
	],
	"nub-nub-cat-9.gif": [
		"blue cat",
		"wide open mouth",
		"67 number",
		"shocked",
		"confused",
		"distorted paws",
		"cursed cat",
		"weird expression",
	],
	"nub-nub-cat-flashbang.gif": [
		"cat in bed",
		"phone screen glow",
		"scrolling at night",
		"insomnia",
		"bright light",
		"blinded",
		"night owl",
		"relatable",
	],
	"nub-nub-cat.gif": [
		"lebron james face",
		"cat body",
		"silhouette transition",
		"lebron cat",
		"funny edit",
		"celebrity cat",
		"smiling lebron",
		"weird meme",
	],
	"nubcat-iwanttocatyou-1.gif": [
		"blue cat",
		"cheering",
		"celebration",
		"happy cat",
		"raised paws",
		"excited",
		"victory",
		"yay",
	],
	"nubcat-iwanttocatyou.gif": [
		"blue cat",
		"cartoon",
		"pinching fingers",
		"tiny amount",
		"squinting",
		"skeptical",
		"examining",
	],
	"oh-yeah-sameer.gif": [
		"man",
		"sunglasses",
		"ponytail",
		"oh yeah text",
		"looking up",
		"realization",
		"excited",
	],
	"oh-yeah.gif": [
		"chris pratt",
		"andy dwyer",
		"parks and recreation",
		"surprised",
		"shocked",
		"mouth open",
		"excited",
	],
	"peace-out-im-out.gif": [
		"animal",
		"ferret",
		"possum",
		"peace out text",
		"peace sign",
		"leaving",
		"goodbye",
	],
	"peace-out-peace-sign.gif": [
		"animal",
		"ferret",
		"possum",
		"peace sign",
		"leaving",
		"goodbye",
		"disappearing",
	],
	"peace-out.gif": [
		"nileseyy niles",
		"black man",
		"peace sign",
		"fading away",
		"disappearing",
		"leaving",
		"goodbye",
	],
	"pedro-pascal-1.gif": [
		"pedro pascal",
		"laughing crying",
		"uncontrollable laughter",
		"emotional roller coaster",
		"funny but sad",
		"hysterical",
		"switch",
		"laughing then crying",
	],
	"pedro-pascal.gif": [
		"pedro pascal",
		"smiling",
		"creepy smile",
		"awkward grin",
		"looking away",
		"hiding pain",
		"staring",
		"fake happy",
	],
	"pentol-stiker-pentol.gif": [
		"white blob",
		"character",
		"typing laptop",
		"concentrating",
		"working hard",
		"blushing",
		"gaming",
		"determined",
	],
	"rolando-ronaldo.gif": [
		"cristiano ronaldo",
		"drinking glass",
		"winking",
		"smooth",
		"celebrity",
		"sipping",
		"charming",
		"confident",
	],
	"sarcastic-clap.gif": [
		"doll puppet",
		"slow clap",
		"sarcastic",
		"creepy",
		"unimpressed",
		"staring",
		"clapping",
		"judgmental",
	],
	"shannon-sharpe-suit-meme.gif": [
		"shannon sharpe",
		"suit and tie",
		"sharp dressed",
		"entrance",
		"flexing",
		"fashionable",
		"confident walk",
		"well dressed",
	],
	"shaq-shimmy.gif": [
		"shaq",
		"shaquille o'neal",
		"shimmy",
		"smirk",
		"shoulder shake",
		"flirtatious",
		"red shirt",
		"suggestive",
	],
	"shock-wtf-joe-coin-emotiguy-stare-serious-disgust-dark.gif": [
		"mike wazowski",
		"one eye",
		"stare",
		"disgust",
		"dark",
		"serious",
		"creepy",
		"judgemental",
	],
	"shocked-ishowspeed.gif": [
		"ishowspeed",
		"speed",
		"shocked",
		"screaming",
		"theater",
		"surprised",
		"overwhelmed",
		"wide mouth",
	],
	"shocked-surprised-1.gif": [
		"cat",
		"shocked",
		"wide eyes",
		"what",
		"disbelief",
		"mouth open",
		"stunned",
		"feline",
	],
	"shocked-surprised.gif": [
		"blinking guy",
		"drew scanlon",
		"sunglasses",
		"wait what",
		"confusion",
		"double take",
		"disbelief",
		"realization",
	],
	"silly-nub-cat-mommy.gif": [
		"blue cat",
		"mommy",
		"blushing",
		"shy",
		"submissive",
		"finger touch",
		"anime style",
		"embarrassed",
	],
	"sillynubcat-nubcat.gif": [
		"blue creature",
		"writing",
		"drawing",
		"notes",
		"study",
		"homework",
		"pencil",
		"focused",
	],
	"small-dihh.gif": [
		"man in suit",
		"cityscape",
		"ambition",
		"dreams",
		"motivational",
		"success",
		"sunset",
		"business",
	],
	"sonic-zesty.gif": [
		"sonic",
		"clapping",
		"laughing",
		"praying",
		"expressions",
		"3d render",
		"sassy",
		"dramatic",
	],
	"spit-in-mouth.webp": [
		"anime woman",
		"side eye",
		"suspicious",
		"skeptical",
		"judging",
		"look back",
		"wavy hair",
		"distrust",
	],
	"squinting-skeptical.gif": [
		"fry",
		"squinting",
		"suspicious",
		"skepticism",
		"investigating",
		"unsure",
		"zoom in",
		"disbelief",
	],
	"stan-twt-evil-chihuahua-1.gif": [
		"chihuahua",
		"creepy smile",
		"wide eyes",
		"unsettling",
		"suspicious",
		"weird dog",
		"grin",
		"intense",
	],
	"stan-twt-evil-chihuahua.gif": [
		"chihuahua",
		"dog",
		"side eye",
		"awkward smile",
		"suspicious",
		"guilty",
		"showing teeth",
		"knowing smile",
	],
	"stop-it-stop.gif": [
		"michael jordan",
		"stop it",
		"get some help",
		"disapproval",
		"intervention",
		"serious",
		"cringe",
	],
	"strange-statement.gif": [
		"fluffy dog",
		"strange statement",
		"confused",
		"blank stare",
		"silent judgment",
		"gang confused",
		"wtf",
	],
	"suenitosgifs-nollywood-roll.gif": [
		"osita iheme",
		"boy",
		"clapping",
		"here we go",
		"excited",
		"anticipation",
		"drama",
		"ready",
	],
	"sueñitosgifs-nollywood-roll.gif": [
		"osita iheme",
		"boy",
		"clapping",
		"here we go",
		"excited",
		"anticipation",
		"drama",
		"ready",
	],
	"suenitosgifs-traumatized-mr-incredible.gif": [
		"mr incredible",
		"traumatized",
		"black and white",
		"those who know",
		"dark realization",
		"despair",
		"uncanny",
		"horror",
	],
	"sueñitosgifs-traumatized-mr-incredible.gif": [
		"mr incredible",
		"traumatized",
		"those who know",
		"black and white",
		"distressed",
		"comparison",
		"realization",
	],
	"sure-oh-ok.gif": [
		"kermit the frog",
		"sipping tea",
		"if you say so",
		"sarcastic",
		"skeptical",
		"none of my business",
		"drinking",
	],
	"sure.gif": [
		"cat",
		"squinting",
		"sure",
		"doubtful",
		"skeptical",
		"suspicious",
		"unconvinced",
	],
	"suspicious-eyes.gif": [
		"heihei",
		"chicken",
		"moana",
		"staring",
		"clueless",
		"blinking",
		"confused",
		"blank stare",
	],
	"sussy-cant-prove-it.gif": [
		"tyrese gibson",
		"fast and furious",
		"eyes on you",
		"watching you",
		"pointing",
		"two fingers",
		"warning",
	],
	"taking-notes.gif": [
		"taking notes",
		"writing",
		"notebook",
		"looking up",
		"pause",
		"realization",
		"black hoodie",
		"hold up",
	],
	"thumbs-up-hamster-cute.gif": [
		"hamster",
		"thumbs up",
		"approval",
		"cute animal",
		"positive vibes",
		"agreement",
		"good job",
	],
	"type-c.jpg": [
		"man in turban",
		"punjabi",
		"sikh",
		"c-type charger",
		"judgmental",
		"serious face",
		"phone humor",
	],
	"up-is-not-jump-knee.gif": [
		"sawing",
		"mannequin leg",
		"kitchen",
		"bizarre",
		"weird diy",
		"strange action",
		"focused expression",
	],
	"viagra.gif": [
		"stick figure",
		"hotdog stand",
		"cyanide and happiness",
		"giant sausage",
		"line cutter",
		"pushing",
		"rude behavior",
		"cartoon slap",
	],
	"what-you-sure.gif": [
		"dachshund",
		"suspicious dog",
		"side eye",
		"skeptical",
		"judgmental look",
		"brown dog",
		"not amused",
	],
	"yellow-emoji-no-no-emotiguy.gif": [
		"yellow emoji",
		"angry face",
		"pointing up",
		"3d character",
		"lecturing",
		"annoyed",
		"actually",
		"tough guy stance",
	],
	"youre-joddamn-right-jod.gif": [
		"walter white",
		"breaking bad",
		"you're goddamn right",
		"joddamn",
		"heisenberg",
		"glasses",
		"goattee",
		"agreement",
	],
}
