export const TITLES_DATABASE: Record<string, string> = {
	"anya-forger.gif": "Anya Forger Smug Smile",
	"baby-laugh-ai-baby.gif": "Laughing Baby",
	"bamboozled-astonished.gif": "Staring Wide Eyed Man",
	"betrayal-phone.gif": "Shocked Blue Cat Phone",
	"blinking-eyes-white-guy.gif": "Blinking White Guy",
	"blush.gif": "Blushing While Reading Phone",
	"bobawooyo-dog-confused.gif": "Surprised Dog Wait What",
	"cast-net-fishing-fall.gif": "Man Falls Throwing Net",
	"cat-huh-cat-huh-etr.gif": "Confused Cat Huh",
	"cat-no.gif": "Cat Saying No",
	"corgi-smirk.gif": "Smirking Corgi",
	"crying-happy.gif": "Crying Wojak Happy Mask",
	"disappointed-fridge-guy.gif": "Druski Rubbing Hands Together",
	"dog-smirk-dark-side.gif": "Suspicious Dog Side Eye",
	"dont-smile-dont-laugh.gif": "Pablo Escobar Biting Lip",
	"druski-got-me.gif": "Druski Laughing Hands Up",
	"druski-shrug-1.gif": "Druski My Bad",
	"druski-shrug-hands-up-druski-shrug.gif": "Druski Shrug With Stick",
	"druski-shrug.gif": "Druski Saying I Tried",
	"druski.gif": "Druski What Do You Mean",
	"fade-away-peace-out.gif": "Disappearing Peace Out",
	"far-cry6-laugh.gif": "Gus Fring Laughing Transition",
	"firat-roblox.gif": "Steph Curry Space Shot",
	"fly-insect.gif": "Fly Rubbing Its Hands",
	"ford-and-ferrari-hats-off.gif": "Enzo Ferrari Hats Off",
	"freaky-sonic-sistertonin.gif": "Sonic The Hedgehog Distressed",
	"freaky-sonic-sonic-the-hedgehog.gif": "Zesty Sonic Praying",
	"ghee-khatam.gif": "Rajkummar Rao Ghee Khatam",
	"go-do-it.gif": "Jack Nicholson Do It",
	"gonna-touch-you-son.gif": "Gonna Touch You Son",
	"goth-baddie-please.gif": "Superbad One Freaky Goth",
	"hamster-cute.gif": "Hamster Looking Around Confused",
	"happy-cat.gif": "Close Up Smiling Cat",
	"heh-huh.gif": "Snowball Rabbit Heh Expression",
	"help.gif": "Shocked Dog Looking At Phone",
	"high-five-walter-white.gif": "Walter White Jesse Pinkman High Five",
	"hooray-letsgo.gif": "Baby Cheering Lets Go",
	"huh-cat.gif": "Tired Orange Cat",
	"i-got-you.gif": "Happy Laughing Baby",
	"i-know-but-i-cant-proof.gif": "Nollywood Men Intense Confrontation",
	"i-use-ai.gif": "No Thanks I Use AI",
	"it-shouldve-been-me-not-him.gif": "Yami Yugi Jealous Outcry",
	"its-me.gif": "Obi-Wan He's Me",
	"its-time-to-stop.gif": "Shaq Time Out Gesture",
	"james-doakes-dexter-dexter.gif": "DMX Driving Intensely",
	"james-harden-bye.gif": "James Harden Side Eye",
	"jumping-hopping.gif": "Dog Falls Into Box",
	"kanye-laugh.gif": "Kanye Kidding Not Kidding",
	"kanye-waste.gif": "Kanye West Mood Shift",
	"ketartine-ragondin.gif": "Screaming Marmot",
	"kétartine-ragondin.gif": "Screaming Marmot",
	"kmt-yeah.gif": "Bearded Man Pouting Face",
	"laughing-then-serious-laughing-then-stoned.gif": "xQc Laughing Transition",
	"lil-dihh.gif": "Sackboy Big Dreams",
	"made-it-to-friday.gif": "Nick Wilde Happy Friday",
	"mario-goth.gif": "Mario and Goth Girl",
	"middle-finger-f-u.gif": "Walter White Middle Finger",
	"money.gif": "Vince McMahon Smelling Money",
	"noot-noot-dark.gif": "Sad Pingu Crying",
	"nope.gif": "Shannon Sharpe Skeptical Face",
	"nub-cat-ohh-i-understand-it-now.gif": "Cat Phone Old Man",
	"nub-cat-uee-aa-u-ee-aa.gif": "Nub Cat Loaf Views",
	"nub-cat-unzips.gif": "Nub Cat Unzips Pants",
	"nub-nub-cat-11.gif": "Nub Cat Blushing Face",
	"nub-nub-cat-12.gif": "Nub Cat Peeking Out",
	"nub-nub-cat-13.gif": "Nub Cat Pointing Up",
	"nub-nub-cat-14.gif": "Blue Cat Demanding Kiss",
	"nub-nub-cat-15.gif": "Blue Cat Licking Moon",
	"nub-nub-cat-16.gif": "Sad Cat Under Arrest",
	"nub-nub-cat-17.gif": "Hand Grabbing Blue Cat",
	"nub-nub-cat-18.gif": "Buff Cats Red Room",
	"nub-nub-cat-19.gif": "Blue Cat Holding Flower",
	"nub-nub-cat-2.gif": "Laughing To Depressed Cat",
	"nub-nub-cat-4.gif": "Playful Threat Blue Cat",
	"nub-nub-cat-6.gif": "Skeptical Blue Cat Gamer",
	"nub-nub-cat-7.gif": "Thinking Of You Cat",
	"nub-nub-cat-8.gif": "Heartfelt Blue Nub Cat",
	"nub-nub-cat-9.gif": "Reaching Out Blue Cat",
	"nub-nub-cat-flashbang.gif": "Bugcat Blasted By Light",
	"nub-nub-cat.gif": "LeBron James Cat Morph",
	"nubcat-iwanttocatyou-1.gif": "Happy Bugcat Dancing",
	"nubcat-iwanttocatyou.gif": "Bugcat Rubbing Tired Eyes",
	"oh-yeah-sameer.gif": "Sameer Oh Yeah",
	"oh-yeah.gif": "Chris Pratt Shocked Face",
	"peace-out-im-out.gif": "Otter Saying Peace Out",
	"peace-out-peace-sign.gif": "Otter Giving Peace Sign",
	"peace-out.gif": "Man Fading Away Peace",
	"pedro-pascal-1.gif": "Pedro Pascal Laughing Crying",
	"pedro-pascal.gif": "Pedro Pascal Smirking Smile",
	"pentol-stiker-pentol.gif": "Pentol Typing On Laptop",
	"rolando-ronaldo.gif": "Cristiano Ronaldo Sipping Drink",
	"sarcastic-clap.gif": "Ken Doll Slow Clap",
	"shannon-sharpe-suit-meme.gif": "Shannon Sharpe Sharp Suits",
	"shaq-shimmy.gif": "Shaq Smirking In Red",
	"shock-wtf-joe-coin-emotiguy-stare-serious-disgust-dark.gif": "Dramatic Emoji Reaching Out",
	"shocked-ishowspeed.gif": "IShowSpeed Shocked At Event",
	"shocked-surprised-1.gif": "Shocked Cat What",
	"shocked-surprised.gif": "Drew Scanlon Wait What",
	"silly-nub-cat-mommy.gif": "Blushing Capoo Cat Mommy",
	"sillynubcat-nubcat.gif": "Capoo Cat Drawing",
	"small-dihh.gif": "Small Dih Big Dreams",
	"sonic-zesty.gif": "Creepy Sonic Expressions",
	"squinting-skeptical.gif": "Fry Squinting Suspiciously",
	"stan-twt-evil-chihuahua-1.gif": "Chihuahua Grinning With Teeth",
	"stan-twt-evil-chihuahua.gif": "Michael Jordan Get Help",
	"stop-it-stop.gif": "Confused Fluffy Dog",
	"strange-statement.gif": "Excited Boy Clapping Hands",
	"suenitosgifs-nollywood-roll.gif": "Excited Boy Clapping Hands",
	"sueñitosgifs-nollywood-roll.gif": "Here We Go Kid Clapping",
	"suenitosgifs-traumatized-mr-incredible.gif": "Mr Incredible Becoming Uncanny",
	"sueñitosgifs-traumatized-mr-incredible.gif": "Mr Incredible Becoming Uncanny",
	"sure-oh-ok.gif": "Kermit Drinking Tea Sarcastic",
	"sure.gif": "Skeptical Cat Saying Sure",
	"suspicious-eyes.gif": "Hei Hei Chicken Expressions",
	"sussy-cant-prove-it.gif": "Uncle Phil Watching You",
	"taking-notes.gif": "Man Writing In Notebook",
	"thumbs-up-hamster-cute.gif": "Hamster Giving Thumbs Up",
	"up-is-not-jump-knee.gif": "Man Sawing Plastic Leg",
	"viagra.gif": "Cyanide And Happiness Line",
	"what-you-sure.gif": "Suspicious Side Eye Dog",
	"yellow-emoji-no-no-emotiguy.gif": "Angry Emoji Pointing Up",
	"youre-joddamn-right-jod.gif": "Walter White Goddamn Right",
}
